# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac2d5b13bd09d7fdcb7db610b6c3c5514d4cce3e82e5a78f3646b22ee166f7abfb0a6c584f5529fb079cae73aa5a54bf86385555be8dcdba9e4b9305620e1d98

test:
  secret_key_base: ef0c034fc42c88928b2a80d11aa6ea83cfa14740c393d6227c5c4249c1a6c77263b5db0eafc9628164e6fd0ae91428316379147761b0fdc8276fc5292a0c2bd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
